installedESLint: true
parser: babel-eslint
extends: airbnb
env:
  browser: true
plugins:
  - react
ecmaFeatures:
  classes: true
  jsx: true
rules:
  global-require: 0
  no-undef: 0
  max-len: 0
  react/prop-types: 1
  react/react-in-jsx-scope: 0
